Space/Space/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stars.urls')),
]

Space/stars/urls.py
from django.urls import path
from . import views

app_name = 'stars'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_logout/', views.user_logout, name='user_logout'),
    path('user_login/', views.user_login, name='user_login'),
    path('new_group/', views.new_group, name='new_group'),
    path('group_details/<str:slug>', views.group_details, name='group_details'),
    path('post/', views.post, name='post'),
    path('my_groups/', views.my_groups, name='my_groups'),
    path('upload/', views.upload, name='upload'),
    path('space_uploads', views.space_uploads, name='space_uploads'),
]

Space/stars/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class Group(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) # Ovo je owner - creator
    title = models.CharField(max_length=256, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True) # Ime grupe sve mala slova i umesto 'space' je '-' - koristi se za url link da pise ime a ne ID objekta
    description = models.CharField(max_length=300)
    created_on = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class User_Groups(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)


class Posts(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    text = models.TextField()

    def __str__(self):
        return self.text


class Pictures(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='space_upload')

    def __str__(self):
        return self.user

Space/stars/forms.py
from django import forms
from .models import User, Group, Posts, Pictures
from django.contrib.auth import password_validation


class Register_form(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput({'placeholder': 'Enter username', 'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput({'placeholder': 'Enter email', 'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput({'placeholder': 'Enter password', 'class': 'form-control'}), validators=[password_validation.validate_password])
    password_confirmation = forms.CharField(widget=forms.PasswordInput({'placeholder': 'Confirm password', 'class': 'form-control'}))

    class Meta():
        model = User
        fields = ['username', 'email', 'password', 'password_confirmation']

    def clean_password_confirmation(self):
        all_clean_data = super().clean()
        try:
            password = all_clean_data['password']
            password_confirmation = all_clean_data['password_confirmation']
        except KeyError:
            pass
        else:
            if password != password_confirmation:
                raise forms.ValidationError('Passwords do not match')


class Login_form(forms.Form):
    username = forms.CharField(widget=forms.TextInput({'placeholder': 'Enter username', 'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput({'placeholder': 'Enter password', 'class': 'form-control'}))


class Group_form(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput({'placeholder': 'Enter title', 'class': 'form-control'}))
    description = forms.CharField(widget=forms.Textarea({'placeholder': 'Enter description', 'class': 'form-control', 'rows': 3}))

    class Meta():
        model = Group
        fields = ['title', 'description']


def get_groups():
    'Uzima grupe koje postoje'
    CHOICES = [(i.id, i.title) for i in Group.objects.all()]
    return CHOICES


class Post_form(forms.ModelForm):
    """ Da ubaci user-a u formu, ali ne vidim primenu!!!!

    def __init__(self, user, *args, **kwargs):
        self.current_user = user
        super(Post_form, self).__init__(*args, **kwargs)
    """
    choose_group = forms.ChoiceField(widget=forms.Select({'class': 'form-control'}), choices=get_groups) # pomocno polje jer treba da se upise Group object a iz liste izbora ne moze da se prenese objekat!!!
    text = forms.CharField(widget=forms.Textarea({'placeholder': 'Enter text', 'class': 'form-control', 'rows': 3}))

    class Meta():
        model = Posts
        fields = ['choose_group', 'text']


class Post_form_within_group(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea({'placeholder': 'Enter text', 'class': 'form-control', 'rows': 3}))

    class Meta():
        model = Posts
        fields = ['text']


class Pictures_form(forms.ModelForm):
    picture = forms.ImageField(label='Upload picture')

    class Meta():
        model = Pictures
        fields = ['picture']

Space/stars/views.py
from django.db.utils import IntegrityError
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from .models import Group, User_Groups, Pictures
from .forms import Register_form, Login_form, Group_form, Post_form, Post_form_within_group, Pictures_form
from django.core.exceptions import ObjectDoesNotExist
from methods import login_redirect
from django.utils.text import slugify

# Create your views here.

def index(request):
    return render(request, 'stars/index.html', {'groups': Group.objects.all()})


def register(request):
    form = Register_form()
    if request.method == 'POST':
        form = Register_form(request.POST)
        if form.is_valid(): # Proverava da li je validna forma koristeci validatore i proverava da li moze elemente forme da upise u bazu
            user = form.save(commit=False)
            user.set_password(request.POST['password'])
            user.save()
            login(request, user)
            return HttpResponseRedirect(reverse('stars:index'))
    return render(request, 'stars/register.html', {'form': form})


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('stars:index'))


def user_login(request):
    form = Login_form()
    if request.method == 'POST':
        form = Login_form(request.POST)
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user:
            if user.is_active:
                login(request, user)
                # return HttpResponseRedirect(reverse('stars:index'))
                return HttpResponseRedirect(login_redirect(request.get_raw_uri()))
            else:
                return HttpResponse('User is not active!')
        else:
            return render(request, 'stars/login.html', {'form': form, 'error': 'Invalid username or password'})
    return render(request, 'stars/login.html', {'form': form})


@login_required
def new_group(request):
    form = Group_form()
    if request.method == 'POST':
        form = Group_form(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.slug = slugify(form.title)
            try:
                form.save()
            except IntegrityError:
                form = Group_form(request.POST)
                return render(request, 'stars/new_group.html', {'form': form, 'error': 'Group with this Title already exists.'})
            else:
                return HttpResponseRedirect(reverse('stars:group_details', args=(form.slug,)))
    return render(request, 'stars/new_group.html', {'form': form})


@login_required
def group_details(request, slug):
    grp = Group.objects.get(slug=slug)
    try:
        grp.user_groups_set.get(user=request.user)
    except ObjectDoesNotExist:
        member = False
    else:
        member = True

    form = Post_form_within_group()
    if request.method == 'POST':
        if 'delete' in request.POST:
            grp.delete()
            return HttpResponseRedirect(reverse('stars:index'))
        elif 'join' in request.POST:
            User_Groups.objects.create(user=request.user, group=grp)
            member = True
        elif 'leave' in request.POST:
            User_Groups.objects.get(user=request.user, group=grp).delete()
            member = False
        elif 'add' in request.POST:
            form = Post_form_within_group(request.POST)
            form = form.save(commit=False)
            form.user = request.user
            form.group = grp
            form.save()
            form = Post_form_within_group()
    return render(request, 'stars/group_details.html', {'group': grp, 'member': member, 'form': form})


@login_required
def post(request):
    form = Post_form()
    if request.method == 'POST':
        form = Post_form(request.POST)
        form = form.save(commit=False)
        form.user = request.user
        form.group = Group.objects.get(id=int(request.POST['choose_group']))
        form.save()
        return HttpResponseRedirect(reverse('stars:group_details', args=(form.group.slug,)))
    return render(request, 'stars/new_post.html', {'form': form})


@login_required
def my_groups(request):
    return render(request, 'stars/my_groups.html', {'groups': request.user.group_set.all()})


@login_required
def upload(request):
    form = Pictures_form()
    if request.method == 'POST':
        picture = request.FILES['picture'].name
        if picture.endswith('.tif') or picture.endswith('.jpg') or picture.endswith('.png'): # Provra da li je odgovarajuci format
            form = form.save(commit=False)
            form.user = request.user
            form.picture = request.FILES['picture']
            form.save()
            return HttpResponseRedirect(reverse('stars:space_uploads'))
        else:
            return render(request, 'stars/upload.html', {'form': form, 'error': 'Select an image file'})
    return render(request, 'stars/upload.html', {'form': form})


@login_required
def space_uploads(request):
    pictures = Pictures.objects.all()
    return render(request, 'stars/space_uploads.html', {'pictures': pictures})

Space/stars/templates/stars/basic.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'stars_css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'stars_css/Glyphs.css' %}">
    <link rel="stylesheet" href="{% static 'stars_css/stars.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Faster+One|Libre+Baskerville|Orbitron" rel="stylesheet">
</head>
<body>


<nav style="background: radial-gradient(#1946d6 10%, #0c305c 50%); position: sticky; top: 0; z-index: 10" class="navbar navbar-expand-lg navbar-dark">
    <ul class="navbar-nav mr-auto ml-4percent">
        <li class="nav-item ml-5percent">
        <a style="font-size: 1.5rem" class="nav-link brand" href="{% url 'stars:index' %}">Space</a>
        </li>
    </ul>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav ml-auto mr-5percent">
            {% if user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'stars:post' %}">Post</a>
            </li>
            <li class="nav-item">
            <a style="margin-right: 30px" class="nav-link" href="{% url 'stars:my_groups' %}">My Groups</a>
            </li>
            <li class="navbar-text">{{ user }}</li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="glyphicon glyphicon-user"></div>
                </a>
                <div style="width: -moz-max-content; width: max-content; left: -10px" class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'stars:user_logout' %}">Logout</a>
                </div>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

{% if user.is_authenticated %}
<div title="Uploads" class="hidden-menu">
    <div style="margin-top: 8px;">
        <div class="burger"></div>
        <div class="burger"></div>
        <div class="burger"></div>
    </div>
</div>

<div class="menu">
    <div><a href="{% url 'stars:upload' %}">Upload picture</a></div>
    <div><a href="{% url 'stars:space_uploads' %}">Uploaded pictures</a></div>
    <div>Hidden menu</div>
</div>
{% endif %}

{% block pictures %}

{% endblock %}

<br><br>
<div class="custom-font" style="margin-right: 3%; margin-left: 3%">
    <div class="row justify-content-around">
      <div style="color: rgba(26, 83, 255, 0.9);" class="col-4"><div style="position: sticky; top: 115px;">{% block col-4 %}{% endblock %}</div></div>
      <div class="col-7">{% block col-8 %}{% endblock %}</div>
    </div>
</div>



<script src="{% static 'stars_js/JQuery.js' %}"></script>
<script src="{% static 'stars_js/ajax_libs_popper.js_1.14.3_umd_popper.js' %}"></script>
<script src="{% static 'stars_js/bootstrap_4.1.1_js_bootstrap.js' %}"></script>
<script src="{% static 'stars_js/jquery-ui.js' %}"></script>
<script src="{% static 'stars_js/stars.js' %}"></script>
</body>
</html>

Space/stars/templates/stars/group_details.html
{% extends 'stars/basic.html' %}


{% block title %}Group details{% endblock %}


{% block col-4 %}
    <h3>Welcome to "{{ group.title }}" group</h3>
    <h6>Created by {{ group.user }} on {{ group.created_on }}</h6><br>
    <form method="post">
    {% csrf_token %}
        {% if user != group.user %}
            {% if not member %}
                <button type="submit" name="join" class="btn btn-warning btn-sm">Join group</button>
            {% else %}
                <button type="submit" name="leave" class="btn btn-warning btn-sm">Leave group</button>
            {% endif %}
        {% else %}
            <span id="confirm-delete" class="confirm-popuptext">
                <span>Are you sure?</span><br>
                <button style="background-color: transparent; border-color: transparent; color: white; cursor: pointer; padding-left: 0;" type="submit" name="delete">Yes</button>
                <span id="confirm-delete-hide" style="cursor: pointer">No</span>
            </span>
            <button id="delete" type="button" class="btn btn-danger btn-sm">Delete group</button>
        {% endif %}
        {% if member or user == group.user %}
            <button style="margin-left: 5px" type="button" id="show-post-form" class="btn btn-success btn-sm">Add post</button>
        {% endif %}
    </form>

    <br><br>
    <form style="display: none" id="post-form" method="post">
    {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <div class="form-row">
                    <div class="col">{{ field }}</div>
                    <div class="col form-error">{{ field.errors }}</div>
                </div>
            </div>
        {% endfor %}
        <button id="post" type="submit" name="add" class="btn btn-primary btn-sm">Post</button>
        <button id="hide-post" style="margin-left: 5px" type="button" class="btn btn-warning btn-sm">Cancel</button>
    </form>
{% endblock %}


{% block col-8 %}
    <div class="col-4-color">
        <h5>{{ group.description }}</h5>
        <br>
        {% for post in group.posts_set.all %}
            <div style="background-color: rgba(167,201,255,0.9); border-radius: 10px; padding: 10px; width: 50%; margin: auto">
                <h6><a href=""><div class="glyphicon glyphicon-user"></div> {{ post.user }}</a></h6>
                <hr>
                <p>{{ post.text | linebreaksbr }}</p>
            </div>
            <br>
        {% endfor %}
    </div>
{% endblock %}

Space/stars/templates/stars/index.html
{% extends 'stars/basic.html' %}


{% block title %}Space{% endblock %}


{% block col-4 %}
    {% if not user.is_authenticated %}
        <h1>Welcome to space blog. Please <a style="color: rgba(87,142,255,0.9);" href="{% url 'stars:register' %}">register</a> or
            <a style="color: rgba(87,142,255,0.9);" href="{% url 'stars:user_login' %}">login</a> to get started.</h1>
    {% else %}
        <h2>Hello {{ user }}</h2>
        <h4>Welcome to the groups page. Select a group with the shared interest or <br><br><a href="{% url 'stars:new_group' %}"><button type="button" class="btn btn-success">
            <span class="glyphicon glyphicon-plus-sign"></span> Create new group</button></a></h4>
    {% endif %}
{% endblock %}


{% block col-8 %}
    {% if user.is_authenticated %}
        {% if groups %}
            {% for group in groups %}
                <div style="padding-left: 25px; padding-right: 25px; padding-top: 15px; padding-bottom: 6px; width: 50%; margin: auto; border-radius: 10px" class="group">
                    <h5><a href="{% url 'stars:group_details' group.slug %}">{{ group.title }}</a></h5>
                    <small>{{ group.description | linebreaksbr }}</small>
                    <hr>
                    <ul style="margin-left: -40px" id="one">
                        <li>Members: {{ group.user_groups_set.count }}</li>
                        <li>Posts: {{ group.posts_set.count }}</li>
                    </ul>
                </div>
                <br>
            {% endfor %}
        {% else %}
            <h5 class="col-4-color">No groups yet</h5>
        {% endif %}
    {% endif %}
{% endblock %}

Space/stars/templates/stars/login.html
{% extends 'stars/basic.html' %}


{% block title %}Login{% endblock %}


{% block col-4 %}
    <h3>Feel in the form to login</h3>
{% endblock %}


{% block col-8 %}
    <form method="post">
    {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label class="col-4-color">{{ field.label_tag }}</label>
                <div class="form-row">
                    <div class="col">{{ field }}</div>
                    <div class="col form-error">{{ field.errors }}</div>
                </div>
            </div>
        {% endfor %}
        <p class="form-error">{{ error }}</p>
    <button type="submit" class="btn btn-primary">Login</button>
    </form>
{% endblock %}

Space/stars/templates/stars/my_groups.html
{% extends 'stars/basic.html' %}


{% block title %}My Groups{% endblock %}


{% block col-4 %}
    <br>
    <a href="{% url 'stars:new_group' %}"><button type="button" class="btn btn-success">
            <span class="glyphicon glyphicon-plus-sign"></span> Create new group</button></a>
{% endblock %}


{% block col-8 %}
    {% if groups %}
        <h4 class="col-4-color">Here is a list of your groups</h4><br>
        {% for group in groups %}
            <div style="padding-left: 25px; padding-right: 25px; padding-top: 15px; padding-bottom: 6px; width: 50%; margin: auto; border-radius: 10px" class="group">
                <h5><a href="{% url 'stars:group_details' group.slug %}">{{ group.title }}</a></h5>
                <small>{{ group.description | linebreaksbr }}</small>
                <hr>
                <ul style="margin-left: -40px" id="one">
                    <li>Members: {{ group.user_groups_set.count }}</li>
                    <li>Posts: {{ group.posts_set.count }}</li>
                </ul>
            </div>
            <br>
        {% endfor %}
    {% else %}
        <h5 class="col-4-color">You haven't created any groups yet!</h5>
    {% endif %}
{% endblock %}

Space/stars/templates/stars/new_group.html
{% extends 'stars/basic.html' %}


{% block title %}New Group{% endblock %}


{% block col-4 %}
    <h3>Feel in the form to create new group</h3>
{% endblock %}


{% block col-8 %}
    <form method="post">
    {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label class="col-4-color">{{ field.label_tag }}</label>
                <div class="form-row">
                    <div class="col">{{ field }}</div>
                    <div class="col form-error">{% if error and forloop.first %}<li style="margin-left: 37px">{{ error }}</li>{% else %}{{ field.errors }}{% endif %}</div>
                </div>
            </div>
        {% endfor %}
        <br>
    <button type="submit" class="btn btn-primary">Create group</button>
    </form>
{% endblock %}

Space/stars/templates/stars/new_post.html
{% extends 'stars/basic.html' %}


{% block title %}New Post{% endblock %}


{% block col-4 %}
    <h3>Feel in the form to post new message</h3>
{% endblock %}


{% block col-8 %}
    <form method="post">
    {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label class="col-4-color">{{ field.label_tag }}</label>
                <div class="form-row">
                    <div class="col">{{ field }}</div>
                    <div class="col form-error">{{ field.errors }}</div>
                </div>
            </div>
        {% endfor %}
    <button type="submit" class="btn btn-primary">Create post</button>
    </form>
{% endblock %}

Space/stars/templates/stars/register.html
{% extends 'stars/basic.html' %}


{% block title %}Register{% endblock %}


{% block col-4 %}
    <h3>Feel in the form to register</h3>
{% endblock %}


{% block col-8 %}
    <form method="post">
    {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label class="col-4-color">{{ field.label_tag }}</label>
                <div class="form-row">
                    <div class="col">{{ field }}</div>
                    <div class="col form-error">{{ field.errors }}</div>
                </div>
            </div>
        {% endfor %}
        <br>
    <button type="submit" class="btn btn-primary">Register</button>
    </form>
{% endblock %}

Space/stars/templates/stars/space_uploads.html
{% extends 'stars/basic.html' %}


{% block title %}Space uploads{% endblock %}


{% block pictures %}
    <br>
    <div class="container">
            {% for picture in pictures %}
                <img src="{{ picture.picture.url }}" alt=""><br>
                <p style="color: rgba(26, 83, 255, 0.9);"><span class="glyphicon glyphicon-user"></span> {{ picture.user }}</p>
                <br><br>
            {% endfor %}
    </div>

{% endblock %}

Space/stars/templates/stars/upload.html
{% extends 'stars/basic.html' %}


{% block title %}Upload{% endblock %}


{% block col-4 %}
   <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                <label class="col-4-color">{{ field.label_tag }}</label>
                <div class="form-row">
                    <div class="col">{{ field }}</div>
                    <div class="col form-error">{{ field.errors }}</div>
                </div>
            </div>
        {% endfor %}
        <p style="color: red">{{ error }}</p>
        <button type="submit" class="btn btn-primary">Upload</button>
    </form>
{% endblock %}